### ISSUE TITLE
Custom exit beats (almost) all levels

### ISSUE THREAD

**Issue by SampaioTS** [AlexNisnevich/untrusted#322]
Something along the lines of

``` javascript
map.defineObject('customExit',{
    symbol : 'c', // not really needed
    onCollision: function (player, game){game._moveToNextLevel();} //function seen in the last level
    //or:
    //onCollision: function (player, game){
    //    game.objects['exit'].onCollision(player,game); //a bit easier to guess
    }
 });
```

will beat pretty much every level if _map.placeObject_'d next to the player. (Maybe adding some verification to check if it was the proper 'exit' object calling the function, somehow? - no idea if this can even be done)

**Comment by mongoose11235813** [comment]
The ability to create new object types is a very powerful tool. You can also use it to make walls that don't affect level validation and hack the game in many other unexpected ways.

**Comment by pppery** [comment]
@mongoose11235813 While the general ability to create new object types is indeed powerful, it is something that a properly designed `validateLevel` function could prevent.  I agree the the customExit thing is a bug that should be fixed, simply because of its universal applicability and the fact that it can't be validated against in-level without completely prohibiting new object types entirely, which is rather extreme.

**Comment by pppery** [comment]
The specific code sample used was broken by a28802149c2af44bf7e8b41e87f70b56fd7c4895, but that can be worked around in a variety of ways, so I am submitting a pull request to fix the general exploit (an object that is not intended to be passed to user code is in one case)
