### ISSUE TITLE
Map object is enumerable

### ISSUE THREAD

**Issue by nametoolong** [AlexNisnevich/untrusted#448]
```js
throw Object.keys(map);
```
`_startOfStartLevelReached` and `_endOfStartLevelReached` are in the output. There is also no protection against calling them anywhere.

**Comment by pppery** [comment]
The real bug here is that 
> There is also no protection against calling [`_startOfStartLevelReached` and `_endOfStartLevelReached`]  anywhere.

Any approach of trying to prevent those strings from ever being accessed by clever user code does not appear to be viable to me. 

(Unless you think private methods showing up in `Object.keys` is a bug for non-security reasons, in which case I could easily fix it once #447 is merged. )

**Comment by nametoolong** [comment]
I think both (calling and enumerating private methods) can be regarded as bugs. It is reasonable to leave `_startOfStartLevelReached` and `_endOfStartLevelReached` accessible by user code, but their showing up is worth a fix – so that a player won't find them at an early level (and ruin all the fun).

**Comment by pppery** [comment]
Making the properties non-enumerable also doesn't prevent `Object.getOwnPropertyNames` from relevaling the existence of these attributes -- as well a a bunch of other private attributes that code is prevented from accessing due to #444

**Comment by nametoolong** [comment]
Oh no. That really doesn't sound good.
